FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD wunderit.jar /opt/wunderit/
EXPOSE 8080
WORKDIR /opt/wunderit/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "wunderit.jar"]
